[WIP] Plugin handling of Ethernet and EthernetETF
open62541/open62541 pull request #3952
Opened 2020-10-08 14:36 UTC by opcua-tsn-team-kalycito

- Removed the separate usage of ETF plugin

- Removed the hardcoding of subscribing interval and socket timeout by creating setDefaultConfing API of ReaderGroup

2020-10-09 05:40 UTC, ccvca requested changes
There are also several permission changes from 0644 to 0755 for .c and .h files. The old permissions seems to be right, as these files are not executable.

2020-10-09 05:40 UTC, ccvca commented on examples/pubsub_realtime/README_pubsub_TSN.txt
> +NOTE: The CSV files will be generated in the build directory containing the timestamp and counter values for benchmarking only after terminating both the applications using �Ctrl + C�
Is this intended?

2020-10-09 05:40 UTC, ccvca commented on plugins/ua_pubsub_ethernet.c
> +    controlMsg->cmsg_len   = CMSG_LEN(sizeof(__u64));
This should be 'UA_UInt64' as well

2020-10-09 05:40 UTC, ccvca commented on plugins/ua_pubsub_ethernet.c
> +        *((__u64 *) CMSG_DATA(controlMsg)) = ethernettransportSettings->transmission_time;
This should be 'UA_UInt64' as well

2020-10-09 05:42 UTC, ccvca commented on examples/pubsub_realtime/README_pubsub_TSN.txt
> +NOTE: The CSV files will be generated in the build directory containing the timestamp and counter values for benchmarking only after terminating both the applications using �Ctrl + C�
![grafik](https://user-images.githubusercontent.com/3939648/95547280-de41d200-0a02-11eb-97a9-9a6559394514.png)
Might be a bug on the file view.

2020-10-09 07:20 UTC, opcua-tsn-team-kalycito commented on plugins/ua_pubsub_ethernet.c
> +        *((__u64 *) CMSG_DATA(controlMsg)) = ethernettransportSettings->transmission_time;
Thanks, done.

2020-11-04 07:53 UTC, opcua-tsn-team-kalycito commented
@jpfr could you re-trigger the failed Windows CI build? The error seems to be in the client_subscription test case which is not related to this PR.

2020-12-11 12:21 UTC, merged