feat(client): Enable clients to securely authenticate to a server using an X.509 certificate
open62541/open62541 pull request #5422
Opened 2022-11-03 13:15 UTC by NoelGraf

- [ ] Provide API function[s] to enable clients to securely authenticate to a server using an X.509 certificate as per OPC-UA specification. E.g. client side to use the “X509IdentityToken” to generate the “userTokenSignature” 
- [ ] Documentation for the new API function[s] and its functionality
- [ ] Example to demonstrating mutual TLS with a client securely connecting to a server using certificate authentication 
- [ ] Automated CI pipeline tests

2022-11-03 13:52 UTC, basyskom-meerkoetter commented on include/open62541/client.h
> +    identityToken->policyId = UA_STRING_ALLOC(policyId);
UA_STRING_ALLOC could also fail due to out of memory. does this also need to be checked?

2022-11-21 12:50 UTC, jpfr reviewed
Looks good!
Comments inline.
A unit test would be nice as well.

2022-11-21 12:50 UTC, jpfr commented on include/open62541/client.h
> +#include <open62541/plugin/securitypolicy_default.h>
Don't include a particular plugin implementation in the core library.

2022-11-21 12:50 UTC, jpfr commented on include/open62541/client.h
> +    UA_SecurityPolicy *securityPolicyAuth;
I prefer with a prefix `authSecurityPolicy`.
Security-Policy-Authentication sounds like authenticating a SecurityPolicy.

2022-11-21 12:50 UTC, jpfr commented on include/open62541/client.h
> +UA_Client_connectCertificate(UA_Client *client, const char *endpointUrl,
For logging in with username/pw we have two options:
1. Use UA_Client_connectUsername
2. Set up the userIdentityToken in the config and connect with UA_Client_connect

The same should possible for certificate authentication.
In the future we will have parsing of the config from some .ini file (JSON).

So I would prefer a public convenience function to set up the client config with cert and key.
And have UA_Client_connectCertificate first set up the config and then call into UA_Client_connect.

2022-11-21 12:50 UTC, jpfr commented on src/client/ua_client_connect.c
> +        retval =
Don't use any specific plugin in the core library.
The SecurityPolicies are already set up for the SecureChannels in the client config.
You can juse use the name to look up the correct policy.

2022-11-21 12:50 UTC, jpfr commented on src/server/ua_services_session.c
> +        UA_X509IdentityToken *userIdentityToken = (UA_X509IdentityToken*)
Is it ensured that this cast is always safe?

2022-11-22 22:38 UTC, jpfr reviewed
Nice, this is making progress.
Comments inline.

2022-11-22 22:38 UTC, jpfr commented on include/open62541/client.h
> +    UA_X509IdentityToken* identityToken = UA_X509IdentityToken_new();
`UA_Client_connectCertificate` is incomplete.
It does nothing with the private key.

Maybe we cannot make this work without a hard link to some specific plugin.
But we will not change the rule that the core library has no dependency on specific plugins.

In that case we could just document how the `authSecurityPolicies` field is to be set up before calling the normal _connect.
And reference `UA_ClientConfig_setCertAuthentication` in a comment.

2022-11-22 22:38 UTC, jpfr commented on include/open62541/client.h
> +    UA_SecurityPolicy *authSecurityPolicies;
Please document when a certificate authentication is used.
If there is a (matching) authSecurityPolicy, do we automatically use that for authentication?
Or does that have to be configured in addition in the userTokenPolicy?

2022-11-22 22:38 UTC, jpfr commented on src/server/ua_services_session.c
> +    const UA_ByteString *localCertificate;
It is easier to read if we don't break up declaration and assignment of the variable.

2022-11-22 22:38 UTC, jpfr commented on include/open62541/client.h
> +    size_t authSecurityPoliciesSize;
I think @mlgiraud said that the same certificates aught to be used for SecureChannel and authentication.
Please check with him.
If that is the case, then we don't need to configure separate authSecurityPoliciesSize.

2022-12-06 19:54 UTC, jpfr commented
Nice!
The code is good.
There is a last issue for the LibreSSL build.
Can be merged once all is green.

2022-12-07 11:22 UTC, mlgiraud requested changes

2022-12-07 11:22 UTC, mlgiraud commented on src/server/ua_services_session.c
> +            checkSignature(server, securityPolicy, tempChannelContext,
Rename securityPolicy to utpSecurityPolicy or something else, indicating that it is the securitypolicy associated with the usertoken.

2022-12-07 11:22 UTC, mlgiraud commented on src/client/ua_client_connect.c
> +    memcpy(userTokenSign.data, userIdentityToken->certificateData.data,
The standard specifies: The data to sign is created by appending the last [serverNonce](https://reference.opcfoundation.org/search/17?t=serverNonce)to the [serverCertificate](https://reference.opcfoundation.org/search/17?t=serverCertificate)specified in the [CreateSession](https://reference.opcfoundation.org/search/17?t=CreateSession)response.

So this should be the remote certificate that is used as data to sign.

2022-12-07 11:22 UTC, mlgiraud commented on src/server/ua_services_session.c
> +               const UA_ExtensionObject *userToken, const UA_SignatureData *signature) {
Remove these new parameters since they are not needed here.

2022-12-07 11:22 UTC, mlgiraud commented on src/server/ua_services_session.c
> +
Remove. The data that is signed is always the server certificate plus the last server nonce.
See: https://reference.opcfoundation.org/Core/Part4/v104/docs/5.6.3
The data to sign is created by appending the last [serverNonce](https://reference.opcfoundation.org/search/17?t=serverNonce)to the [serverCertificate](https://reference.opcfoundation.org/search/17?t=serverCertificate)specified in the [CreateSession](https://reference.opcfoundation.org/search/17?t=CreateSession)response.

2022-12-08 14:09 UTC, merged