[WIP] Fix PubSub decoding of custom datatypes.
open62541/open62541 pull request #5681
Opened 2023-03-14 12:47 UTC by basyskom-dege

The decoding of custom data types did not work because the helper functions for decoding the payload of a network message set the `UA_DataTypeArray` argument to NULL. 

I fixed this problem by not using the helper functions and instead use `UA_decodeBinaryInternal(...)` directly with the given data type and the `UA_DataTypeArray`. 

To not break existing code, I added a wrapper function. (See comments)

I also added a new test that covers all the custom data types. I used the definitions from` check_types_custom.c` and `check_pubsub_encoding.c`

2023-03-14 12:49 UTC, basyskom-dege commented on src/pubsub/ua_pubsub_networkmessage.c
> +                               UA_NetworkMessage* dst, const UA_DataTypeArray *customTypes) {
I added a new function that is called by the original `UA_NetworkMessage_decodeBinary` function but with the `UA_DataTypeArray` set to NULL. 

If you are using a custom data type in a network message, you can use the new function `UA_NetworkMessage_decodeBinary_custom` and provide your `UA_DataTypeArray`.

2023-03-15 16:19 UTC, jpfr requested changes
Very nice!
However, please don’t provide this wrapper function. Every caller should have to say explicitly “I don’t want to use any custom type definition”.

Also, wherever we use the decoding in a server or client context, always forward the custom type from the configuration.

One such case is marked with an comment below.

2023-03-16 08:54 UTC, basyskom-dege commented on src/pubsub/ua_pubsub_reader.c
> +    rv = UA_NetworkMessage_decodePayload(buffer, pos, nm, NULL);
Will do. I wasn't sure if there's a need for this without a server or client context. 

`UA_NetworkMessage_decodeBinary()` should not use any custom data types then? The function does not have the server object so we cannot access the custom types from the configuration.

If you want to use custom types you have to use the `decodeNetworkMessage` from `ua_pubsub_reader.c` ?

2023-03-16 10:42 UTC, jpfr commented on src/pubsub/ua_pubsub_reader.c
> +    rv = UA_NetworkMessage_decodePayload(buffer, pos, nm, NULL);
> UA_NetworkMessage_decodeBinary() should not use any custom data types then? The function does not have the server object so we cannot access the custom types from the configuration.

This method should take the custom types as an argument.
But just the custom types, not entire server object.

2023-03-16 11:54 UTC, basyskom-dege commented on src/pubsub/ua_pubsub_reader.c
> +    rv = UA_NetworkMessage_decodePayload(buffer, pos, nm, NULL);
Okay. Done. This broke some tests but I just set the argument to NULL for those tests since they are not using any custom types.

2023-03-21 16:42 UTC, merged

2023-03-21 16:42 UTC, jpfr commented
Nice!